# Day12
# Numpy Library

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
arr = np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## Dimension in array

In [6]:
arr = np.array(69)
print(arr)
print(type(arr))
print(arr.ndim)
               

69
<class 'numpy.ndarray'>
0


## 1D Array

In [15]:
arr = np.array([1.2, 4.5, 6.7, 8.9])
print(arr)
print(type(arr))
print(arr.ndim)

[1.2 4.5 6.7 8.9]
<class 'numpy.ndarray'>
1


In [17]:
arr = np.array([[1.2, 4.5, 6.7, 8.9],[1,2,3,4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
arr = np.array([[12, 45, 7, 9],[1,2,3,4]])
print(arr)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [29]:
arr = np.array([[12, 45, 7, 9],[1,2,3,4]])
print(arr)
print(type(arr))
print(arr.ndim)

[[12 45  7  9]
 [ 1  2  3  4]]
<class 'numpy.ndarray'>
2


In [31]:
arr = np.array([[12, 45, 7, 9],[1.2,2.3,3.4,4.5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[12.  45.   7.   9. ]
 [ 1.2  2.3  3.4  4.5]]
<class 'numpy.ndarray'>
2


## 3D array

In [36]:
arr = np.array([[[1, 5, 7, 9],[1,2,3,4]],[[1,2,3,4],[2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 5 7 9]
  [1 2 3 4]]

 [[1 2 3 4]
  [2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [71]:
arr = np.array([[[1, 5, 7, 9]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 5 7 9]]]
<class 'numpy.ndarray'>
3


In [44]:
import numpy as np
a = np.array(67)
b = np.array([1,2,3])
c = np.array([[1,3,4],[12,7,9]])
d = np.array([[[3,7,6],[8,2,4]],[[4,8,2],[1,4,7]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [48]:
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)
print(type(arr))
print(arr.ndim)


[[[[[1 2 3 4]]]]]
<class 'numpy.ndarray'>
5


In [50]:
arr = np.array([[[[[1,2,3,4]]]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[1 2 3 4]]]]]
<class 'numpy.ndarray'>
5


 ## get third, sixth and 8th element from the array

In [56]:
arr = np.array([1,3,7,4,5,6,9,8])
print(arr[2])
print(arr[5])
print(arr[7])



7
6
8


In [58]:
arr = np.array([[1,3,7,4],[6,9,8,5]])
print(arr[0,1])

3


In [60]:
arr = np.array([[1,3,7,4],[6,9,8,5]])
print(arr[0,3])


4


In [62]:
arr = np.array([[1,3,7,4],[6,9,8,5]])
print(arr[1,0])

6


In [68]:
arr = np.array([[1,3,7,4],[6,9,8,5]])
a = print(arr[0,0])
b = print(arr[1,3])
print(arr[0,0]+arr[1,3])

1
5
6


## Access 3D array

In [73]:
arr = np.array([[[3,7,6],[8,2,4]],[[4,8,2],[1,5,7]]])
print(arr[1,1,1])

5


In [75]:
arr = np.array([[[3,27,6],[8,32,4]],[[4,9,2],[1,5,7]]])
print(arr[0,1,1])


32


# Day 13

## slicing of numpy arrays

In [78]:
arr = np.array([4,5,8,9,1,7,3])
print(arr[2:4])

[8 9]


arr = np.array([4,5,8,9,1,7,3])
print(arr[0:1])

In [84]:
arr = np.array([4,5,8,9,1,7,3,2])
print(arr[::2])

[4 8 1 3]


## slicing in 2D array

In [87]:
arr = np.array([[1,3,4,9],[12,7,9,45]])
print(arr[1,0:3])

[12  7  9]


In [89]:
arr = np.array([[1,3,4,9],[12,7,9,45]])
print(arr[0,1:3])

[3 4]


## checking the data type of an array

In [94]:
arr = np.array([4,5,8,9,1,7,3,2])
print(arr.dtype)

int32


In [96]:
arr = np.array(["hello","how","aromco","apple","code"])
print(arr.dtype)

<U6


## creating array with defined data type

In [101]:
arr = np.array([1,2,3,4,5],dtype ='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


## create an array with data type 4 byte integer

In [104]:
arr = np.array([1,2,3,4,5],dtype ='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


# Numpy array shape

## print the shape of 2d array

In [114]:
arr = np.array([[1,3,4],[12,7,9]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  3  4]
 [12  7  9]]
2
(2, 3)


In [118]:
arr = np.array([[[1,3,4], [12,7,9], [12,7,9]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  3  4]
  [12  7  9]
  [12  7  9]]]
3
(1, 3, 3)


## joining Numpy Array

In [125]:
arr1 = np.array([4,5,8,9])
arr2 = np.array([6,1,3,7])
arr = np.concatenate((arr1, arr2))
print(arr)

[4 5 8 9 6 1 3 7]


## joining 2D array

In [130]:
arr1 = np.array([[4,5,8], [6,1,3]])
arr2 = np.array([[6,1,7], [2,7,9]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[4 5 8 6 1 7]
 [6 1 3 2 7 9]]


In [132]:
arr1 = np.array([[4,5,8], [6,1,3]])
arr2 = np.array([[6,1,7], [2,7,9]])
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[[4 5 8]
 [6 1 3]
 [6 1 7]
 [2 7 9]]


# Splitting Numpy Array

## splitting into 3 part

In [138]:
arr = np.array([4,5,8,6,1,3])
newarr = np.array_split(arr,3)
print(newarr)

[array([4, 5]), array([8, 6]), array([1, 3])]


In [140]:
arr = np.array([4,5,8,6,1,3])
newarr = np.array_split(arr,2)
print(newarr)

[array([4, 5, 8]), array([6, 1, 3])]


In [142]:
arr = np.array([4,5,8,6,1])
newarr = np.array_split(arr,2)
print(newarr)

[array([4, 5, 8]), array([6, 1])]


In [144]:
arr = np.array([4,5,8,6,1])
newarr = np.array_split(arr,3)
print(newarr)

[array([4, 5]), array([8, 6]), array([1])]


# ravel and flatten

## convert multidimensional array into 1D array

In [161]:
arr = np.array([[[4,5,8],[6,1,3],[6, 1, 3]]])
print(arr)
print("old dimension is", arr.ndim)
newarr = arr.ravel()
print(newarr)
print("new dimesion is", newarr.ndim)

[[[4 5 8]
  [6 1 3]
  [6 1 3]]]
old dimension is 3
[4 5 8 6 1 3 6 1 3]
new dimesion is 1


In [163]:
arr = np.array([[[4,5,8],[6,1,3],[6, 1, 3]]])
print(arr)
print("old dimension is", arr.ndim)
newarr = arr.flatten()
print(newarr)
print("new dimesion is", newarr.ndim)

[[[4 5 8]
  [6 1 3]
  [6 1 3]]]
old dimension is 3
[4 5 8 6 1 3 6 1 3]
new dimesion is 1


In [167]:
arr = np.array([[[[4,5,8],[6,1,3],[6, 1, 3]]]])
print(arr)
print("old dimension is", arr.ndim)
d = arr.ravel()
print(d)
print("new dimension is", d.ndim)

[[[[4 5 8]
   [6 1 3]
   [6 1 3]]]]
old dimension is 4
[4 5 8 6 1 3 6 1 3]
new dimension is 1


In [175]:
arr = np.array([4,5,8,6,1,2,7,6,3,1,2,3,4,9])
print(arr)
x = np.unique(arr)
print(x)

[4 5 8 6 1 2 7 6 3 1 2 3 4 9]
[1 2 3 4 5 6 7 8 9]


In [177]:
arr = np.array([4,5,8,6,1,2,7,6,3,1,2,3,4,9])
print(arr)
x = np.unique(arr,return_index = True)
print(x)

[4 5 8 6 1 2 7 6 3 1 2 3 4 9]
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 4,  5,  8,  0,  1,  3,  6,  2, 13], dtype=int64))


In [179]:
arr = np.array([4,5,8,6,1,3])
x = np.delete(arr,[0])
print(x)

[5 8 6 1 3]


In [181]:
arr = np.array([4,5,8,6,1,3])
x = np.delete(arr,[1])
print(x)

[4 8 6 1 3]


In [187]:
arr = np.array([[4,5,8,6,1,3],[6,3,1,2,3,4],[4,5,8,6,1,2]])
print(arr)
print(arr.ndim)
z = np.delete(arr, 0, axis=0)
print(z)



[[4 5 8 6 1 3]
 [6 3 1 2 3 4]
 [4 5 8 6 1 2]]
2
[[6 3 1 2 3 4]
 [4 5 8 6 1 2]]


In [189]:
arr = np.array([[4,5,8,6,1,3],[6,3,1,2,3,4],[4,5,8,6,1,2]])
print(arr)
print(arr.ndim)
z = np.delete(arr, 1, axis=0)
print(z)

[[4 5 8 6 1 3]
 [6 3 1 2 3 4]
 [4 5 8 6 1 2]]
2
[[4 5 8 6 1 3]
 [4 5 8 6 1 2]]


In [191]:
arr = np.array([[4,5,8,6,1,3],[6,3,1,2,3,4],[4,5,8,6,1,2]])
print(arr)
print(arr.ndim)
z = np.delete(arr, 1, axis=1)
print(z)

[[4 5 8 6 1 3]
 [6 3 1 2 3 4]
 [4 5 8 6 1 2]]
2
[[4 8 6 1 3]
 [6 1 2 3 4]
 [4 8 6 1 2]]
